# Generated by Django 4.2 on 2023-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
