# Generated by Django 4.2 on 2023-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_image',
            field=models.ImageField(default=0, upload_to='media/qr_codes/'),
        ),
    ]
