# Generated by Django 4.2 on 2023-05-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_customuser_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_image',
        ),
    ]
