# Generated by Django 4.2 on 2023-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(upload_to='media/qr_codes/'),
        ),
    ]
